@startuml
class Пользователь {
    +id : UUID
    +имя : String
    +email : String
    +пароль : String
    +пол : String
    +телефон : String
    +датаРождения : Date
    +адрес : Адрес
    +предпочтения : String
}

class Поездка {
    +id : UUID
    +времяВыезда : Date
    максимумПассажиров: byte
    датаСоздания: Date
    статус: String
    +редактируемый: Boolean // возможность редактирования
}

class Маршрут {
    +id : UUID
    +начальнаяТочка : String
    +конечнаяТочка : String
    +дата : Date
    оценочнаяПродолжительность: short
}

class Бронирование {
    +id : UUID
    +количествоМест : byte
    +статус : String
    датаБронирования: Date
    +номерПаспорта: String
    датаОкончанияСрокаПаспорта: Date
}



class Оценка {
    +id : UUID
    +рейтинг : int
    +комментарий : String
    +дата: Date
}


' Определение встраиваемого типа Адрес (Value Object)
class Адрес <<value object>> {
  -улица : String
  -индекс : String
  -город : String
}


Пользователь --> "0..*" Поездка
Поездка --> "1..*" Бронирование
Поездка --> "1" Маршрут
Поездка --> "0..*" Оценка
Пользователь *-- "1" Адрес : содержит > ' Композиция

@enduml


