@startuml
class Пользователь {
    +id : int
    +имя : String
    +email : String
    +пароль : String
    +пол : String
    +телефон : String
    +датаРождения : Date
    +адрес : String
    +предпочтения : String
}

class Поездка {
    +id : int
    +времяВыезда : Date
    максимумПассажиров: byte
    датаСоздания: Date
    статус: String
    +редактируемый: Boolean // возможность редактирования
}

class Маршрут {
    +id : int
    +начальнаяТочка : String
    +конечнаяТочка : String
    +дата : Date
    оценочнаяПродолжительность: short
}

class Бронирование {
    +id : int
    +количествоМест : byte
    +статус : String
    датаБронирования: Date
    +номерПаспорта: String
    датаОкончанияСрокаПаспорта: Date
}



class Оценка {
    +id : int
    +рейтинг : int
    +комментарий : String
    +дата: Date
}

Пользователь --> "0..*" Поездка
Поездка --> "1..*" Бронирование
Поездка --> "1" Маршрут
Поездка --> "0..*" Оценка

@enduml


