@startuml
package "Модуль аутентификации" {
  [Модуль входа]
  [Модуль регистрации]
}

package "Модуль поездок" {
  [Модуль отображения поездок]
  [Модуль создания поездок]
}

package "Модуль бронирования" {
  [Бронирование]
}

package "Модуль уведомлений" {
  [Уведомления]
}

[Модуль входа] --> [Модуль регистрации]
[Модуль отображения поездок] --> [Модуль создания поездок]
[Бронирование] --> [Модуль отображения поездок]
[Бронирование] --> [Уведомления]

@enduml

