@startuml
entity Пользователь {
    +id : UUID <<PK>>
    +имя : String
    +email : String
    +пароль : String
    +пол : String
    +телефон : String
    +датаРождения : Date
    +адрес : Address
    +предпочтения : String
}

entity Поездка {
    +id : UUID <<PK>>
    +времяВыезда : Date
    +максимумПассажиров : byte
    +датаСоздания : Date
    +статус : String
    +редактируемый : Boolean
    +пользовательId : String <<FK>>
    +маршрутId : UUID <<FK>>
}

entity Маршрут {
    +id : UUID <<PK>>
    +начальнаяТочка : String
    +конечнаяТочка : String
    +дата : Date
    +оценочнаяПродолжительность : short
}

entity Бронирование {
    +id : UUID <<PK>>
    +количествоМест : byte
    +статус : String
    +датаБронирования : Date
    +номерПаспорта : String
    +датаОкончанияСрокаПаспорта : Date
    +поездкаId : UUID <<FK>>
    +пользовательId : UUID <<FK>>
}

entity Оценка {
    +id : UUID <<PK>>
    +рейтинг : int
    +комментарий : String
    +дата : Date
    +поездкаId : UUID <<FK>>
}

Пользователь ||--o{ Поездка : создает
Поездка ||--o{ Бронирование : содержит
Поездка ||--o{ Оценка : имеет
Поездка }|--|| Маршрут : использует

@enduml

