@startuml
entity Пользователь {
    +id : int
    +имя : String
    +email : String
}



entity Поездка {
    +id : int
    +времяВыезда : Date
    максимумПассажиров: int
    датаСоздания: Date
    статус: String
}

entity Маршрут {
    +id : int
    +начальнаяТочка : String
    +конечнаяТочка : String
    +дата : Date
    оценочнаяПродолжительность: int
}

entity Бронирование {
    +id : int
    +количествоМест : int
    +статус : String
    датаБронирования: Date
}

entity Сообщение {
    +id : int
    +текст : String
    +датаОтправки : Date
    статусПрочтения: Boolean
}

entity Оценка {
    +id : int
    +рейтинг : int
    +комментарий : String
    дата: Date
}

Пользователь --> "0..*" Поездка : имеет
Поездка --> "1..*" Бронирование : содержит
Поездка --> "1" Маршрут : имеет
Пользователь o-- "0..*" Сообщение : отправляет/получает
Поездка --> "0..*" Оценка : имеет

@enduml

