@startuml
entity Пользователь {
    +id : int
    +имя : String
    +email : String
    +телефон : String
    +датаРождения : Date
    +адрес : String
    +предпочтения : String
}

entity Поездка {
    +id : int
    +времяВыезда : Date
}

entity Маршрут {
    +id : int
    +начальнаяТочка : String
    +конечнаяТочка : String
    +дата : Date
}

entity Бронирование {
    +id : int
    +количествоМест : int
    +статус : String  // e.g., "Забронировано", "Отменено"
}

entity Сообщение {
    +id : int
    +отправительId : int // Ссылка на id отправителя
    +получательId : int // Ссылка на id получателя
    +текст : String
    +датаОтправки : Date
}

entity Оценка {
    +id : int
    +рейтинг : int
    +комментарий : String
}

Пользователь --> "0..*" Поездка : имеет
Поездка --> "1..*" Бронирование : содержит
Поездка --> "1" Маршрут : имеет
Пользователь o-- "0..*" Сообщение : отправляет/получает
Поездка --> "0..*" Оценка : имеет

@enduml

