@startuml
'https://plantuml.com/use-case-diagram

left to right direction

actor Неавторизованный_пользователь
actor Пользователь
actor Водитель
actor Система


Неавторизованный_пользователь --> (Регистрация)
Неавторизованный_пользователь --> (Поиск попутчика)

Пользователь --> (Авторизация)
Пользователь --> (Поиск попутчика)
Пользователь --> (Создание поездки)

Пользователь --> (Бронирование места)
(Бронирование места) .left.> (Отмена брони) : Include
(Бронирование места) .right.> (Оплата поездки) : Include

Пользователь --> (Оценка поездки)
Пользователь --> (Просмотр истории поездок)
Пользователь --> (Управление профилем)
Пользователь --> (Отправка и получение сообщений)

Водитель -left-|> Пользователь
Водитель --> (Редактирование поездки)
(Редактирование поездки) ..> (Удаление поездки)


(Авторизация) <-- Система
(Поиск попутчика) <-- Система
(Создание поездки) <-- Система
(Бронирование места) <-- Система
(Оценка поездки) <-- Система
(Просмотр истории поездок) <-- Система
(Управление профилем) <-- Система
(Отправка и получение сообщений) <-- Система
(Регистрация) <-- Система
(Редактирование поездки) <-- Система

@enduml