@startuml

left to right direction


actor Пользователь

actor Система




Пользователь --> (Поиск попутчика)
Пользователь --> (Создание поездки)
(Создание поездки) .left.> (Отправка и получение сообщений) : Include

Пользователь --> (Бронирование места)
(Бронирование места) .up.> (Отмена брони) : Include
(Бронирование места) <.. (Оплата поездки) : Extend
(Бронирование места) .right.> (Отправка и получение сообщений) : Include
(Бронирование места) <|-- (Бронирование одного места)
(Бронирование места) <|-- (Бронирование нескольких мест)

Пользователь --> (Оценка поездки)
Пользователь --> (Просмотр истории поездок)
Пользователь --> (Управление профилем)


Пользователь --> (Управление поездкой)
(Управление поездкой) ..> (Удаление поездки) : Include
(Управление поездкой) ..> (Редактирование поездки) : Include



(Поиск попутчика) <-- Система
(Создание поездки) <-- Система
(Бронирование места) <-- Система
(Оценка поездки) <-- Система
(Просмотр истории поездок) <-- Система
(Управление профилем) <-- Система
(Управление поездкой) <-- Система

@enduml
